import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cookies } from 'next/headers'
import { COOKIE_NAME } from './constants'
import Navbar from './navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookiesStore = cookies();
  const session = cookiesStore.get(COOKIE_NAME);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar session={session}/>
        {children}
      </body>
    </html>
  )
}
